/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppVocabularyRouteImport } from './routes/_app.vocabulary'
import { Route as AppVocabSetsRouteImport } from './routes/_app.vocab-sets'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppVocabularyRoute = AppVocabularyRouteImport.update({
  id: '/vocabulary',
  path: '/vocabulary',
  getParentRoute: () => AppRoute,
} as any)
const AppVocabSetsRoute = AppVocabSetsRouteImport.update({
  id: '/vocab-sets',
  path: '/vocab-sets',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/vocab-sets': typeof AppVocabSetsRoute
  '/vocabulary': typeof AppVocabularyRoute
}
export interface FileRoutesByTo {
  '/vocab-sets': typeof AppVocabSetsRoute
  '/vocabulary': typeof AppVocabularyRoute
  '/': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_app/vocab-sets': typeof AppVocabSetsRoute
  '/_app/vocabulary': typeof AppVocabularyRoute
  '/_app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/vocab-sets' | '/vocabulary'
  fileRoutesByTo: FileRoutesByTo
  to: '/vocab-sets' | '/vocabulary' | '/'
  id: '__root__' | '/_app' | '/_app/vocab-sets' | '/_app/vocabulary' | '/_app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/vocabulary': {
      id: '/_app/vocabulary'
      path: '/vocabulary'
      fullPath: '/vocabulary'
      preLoaderRoute: typeof AppVocabularyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/vocab-sets': {
      id: '/_app/vocab-sets'
      path: '/vocab-sets'
      fullPath: '/vocab-sets'
      preLoaderRoute: typeof AppVocabSetsRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppVocabSetsRoute: typeof AppVocabSetsRoute
  AppVocabularyRoute: typeof AppVocabularyRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppVocabSetsRoute: AppVocabSetsRoute,
  AppVocabularyRoute: AppVocabularyRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
